config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy,:show]
  resources :users
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  #beforedestroyは他のプログラムとの関係でうまく働かないことがあるので、先頭に持ってくる
  #before_destroyは、戻り値がnilだと作動しないので注意が必要。
  before_destroy :do_not_destroy_admin_user
  validates :name,  presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 60 },
  # メールアドレスが正しい形式で入力されているかのバリデーション
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  # 大文字小文字を区別するためにすべて小文字として判定するための破壊的メソッドdowncase!
  before_validation { email.downcase! }
  # 下記は、bcryptをbundle installすると使用可能になるメソッドで、password_digestに暗号化したパスワードを保存してくれるものです。
  has_secure_password
  # ユーザーはポストに対しても１対多の関係により、hasmanyが必要という解釈。
  #関連するものすべてを消去するためにdependent:destroys
  has_many :tasks, dependent: :destroy
  enum admin: { 管理者: true, 一般ユーザー: false}

  def do_not_destroy_admin_user
    #削除する名前が
    #管理者が1人以下になった場合、管理者を削除できないようにする
    admins = User.select(:admin).pluck(:admin).count("管理者")
      throw(:abort) if admins == 1
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user?
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
        # ブラウザのcookieにハッシュ化したユーザーidを保存
      redirect_to admin_users_path, notice: "新規ユーザーを作成しました"
    else
      render :new
    end

  end

  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user.id), notice: "ユーザーデータを更新しました"
    else
      render :edit
    end
  end
  def show
    #自分以外のユーザーのページにアクセスした場合、タスク一覧に遷移する
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除しました'
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  #ここは管理者画面なので、,adminカラムのデータ変更も許可している
  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation, :admin)
  end
  def admin_user?
    unless current_user.admin == "管理者"
      redirect_to root_path, notice: "あなたは管理者ではありません"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
      #ログインしていた一般ユーザーだった場合
    if logged_in?
      redirect_to tasks_path, notice: "ログインしている人はユーザー作成できません"
    end
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
        # ブラウザのcookieにハッシュ化したユーザーidを保存
      if @user.admin == "管理者"
        redirect_to admin_users_path
      else
        session[:user_id] = @user.id
        redirect_to user_path(@user.id), notice: "ユーザー情報を登録しました"
      end
    else
      render :new, notice: "ユーザー登録に失敗したよ"
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を更新したやで"
    else
      render :edit
    end
  end
  def show
    current_user
    @user = User.find(params[:id])
    #自分以外のユーザーのページにアクセスした場合、タスク一覧に遷移する
    unless current_user.id == @user.id
      redirect_to tasks_path, notice: "自分以外のタスクは見れません"
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation,)
  end
end

app/views/admin/users/edit.html.erb
<%= form_with(model: @user, url: admin_user_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "件のエラーが発生しました") %></h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <%= form.label :管理者権限 %>
    <%= form.select :admin, User.admins.keys, include_blank: true %>
    <button type="button" class = "btn btn-priority">
    <%= form.submit "アカウントを更新する" %>
    </button>
<% end %>

app/views/admin/users/index.html.erb
<p id ="notice"><%= notice %></p>
<h1>管理者用ユーザーページ</h1>
<button type="button" class = "btn btn-priority"><%= link_to '管理者新規登録画面',new_admin_user_path %></button>

<% @users.each do |user| %>
<table>
  <thead id= "status_color">
    <tr>
      <th> ユーザーid </th>
      <th> ユーザーネーム </th>
      <th> 管理者権限 </th>
      <th> ユーザーのタスク数 </th>
    </tr>
  </thead>
  <tbody>
    <tr id="content_color">
      <td><%= user.id  %></td>
      <td><%= user.name %></td>
      <td><%= user.admin %></td>
      <td>タスクの数<%= user.tasks.count %></td>
      <td><button type="button" class = "btn btn-priority">
        <%= link_to '詳細',admin_user_path(user.id) %></button></td>
        <td><button type="button" class = "btn btn-priority">
          <%= link_to 'ユーザー設定',edit_admin_user_path(user.id) %></button></td>
          <td><button type="button" class = "btn btn-danger">
            <%= link_to '削除',admin_user_path(user.id), method: :delete, data: { confirm: '削除していいですか?' } %></button></td>
          </tr>
        </tbody>
      </table>
      <% end %>

app/views/admin/users/new.html.erb
<h1>管理者用ページユーザー作成ページ</h1>
<p id ="notice"><%= notice %></p>
<div class = "text-center">
<%= form_with model: @user, url: admin_users_path,  local: true do |f| %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.label :管理者権限 %>
  <div id="admin">
  <%= f.select :admin, User.admins.keys, include_blank: true %>
  </div>
  <br>
  <button type="button" class = "btn btn-priority">
  <%= f.submit "アカウントを作成する" %>
  </button>
<% end %>
</div>

app/views/admin/users/show.html.erb
<p id="notice"></p>
<h3><%= @user.name %>さん</h3>
<h3>メールアドレス: <%= @user.email %></h3>
<table>
  <thead>
    <tr>
      <th id="th_color"><%= t('view.Task name') %></th>
      <th id="th_color"><%= t('view.Content') %></th>
      <th id="th_color"><%= t('view.Time limit') %></th>
      <th id="th_color"><%= t('view.Priority') %></th>
      <th id="th_color"><%= t('view.Status') %></th>
      <th id="th_color"><%= t('view.label') %></th>
      <th id="th_color"><%= t('view.Created_at') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
    <tr>
      <td id="task_color"><%= task.task_name%></td>
      <td id="content_color"><%= task.content%></td>
      <td id="time_limit_color"><%= task.time_limit%></td>
      <td id="priority_color"><%= task.priority %></td>
      <td id="status_color"><%= task.status %></td>
      <td id="label_color">
        <% task.labels.each do |label| %>
        <%= label.label_name %>
        <% end %>
      </td>
      <td><%= task.created_at.to_s(:datetime_jp)%></td>
      <td>  <button type="button" class = "btn btn-priority"><%= link_to '詳細を確認する', task_path(task.id) %></td>
        <td>  <button type="button" class = "btn btn-priority"><%= link_to "投稿を編集する", edit_task_path(task.id) %></td>
          <td>  <button type="button" class = "btn btn-priority"><%= link_to '投稿を削除する', task_path(task.id), method: :delete %></td>
                <% end %>
              </tbody>
            </table>
            <div id ="footer_top">
              <%= link_to "投稿一覧画面にもどる", tasks_path %>
              <%# <%= link_to "ユーザー情報を編集する", edit_user_path(@user.id) %>
            </div>